### PR TITLE
Create rovel.json

### PR DESCRIPTION
**Pull request by sayantan300**

### CODE REVIEW

**Comment by sayantan300** [comment]
Hi there, pls add my theme under rovel name
Thanks for creating discord term

**Comment by Rexogamer** [comment]
Just outta curiosity, mind sending a screenshot?

**Comment by cloudrex** [comment]
@sayantan300 A screenshot would most definitely help.

**Comment by sayantan300** [comment]
Sorry but I use a phone to code so that might be a problem, it would be
good if u would like to check it out

**Comment by Rexogamer** [comment]
I’m on phone too which I why I wanted to see a screenshot

**Comment by sayantan300** [comment]
How to show u ?

**Comment by Rexogamer** [comment]
Try and get access to a PC and test your changes

**Comment by sayantan300** [comment]
How to build it?

**Comment by chroventer** [comment]
Do not change and commit unrelated files. (npm-publish.yml)

**Comment by atlx** [comment]
@sayantan300, Thank you for the GitHub workflow! Do keep in mind, that like @chroventer mentioned, make sure you separate future contributions into their own pull request(s).

**Pull request merged**
